config/routes.rb
Rails.application.routes.draw do
  root :to => "catalogs#index"
  resources :catalogs do
  	resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catalog.rb
class Catalog < ApplicationRecord

	has_many :products, dependent: :destroy

	def quantity
		i = 0
		if self.products
			self.products.each do |prod|
				i = i + 1
			end
		end
		return i
	end
end

app/models/product.rb
class Product < ApplicationRecord

	belongs_to :catalog

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_action :set_catalog, only: [:show, :edit, :update, :destroy]

  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = Catalog.all
    @products = Product.all
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show
  end

  # GET /catalogs/new
  def new
    @catalog = Catalog.new
  end

  # GET /catalogs/1/edit
  def edit
  end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(catalog_params)
    @catalog.save
  end

  # PATCH/PUT /catalogs/1
  # PATCH/PUT /catalogs/1.json
  def update
    @catalog.update(catalog_params)
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catalog_params
      params.require(:catalog).permit(:name, :code, :number_of_products)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.catalog_id = params[:catalog_id]
    @product.save
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.update(product_params)
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :code, :description, :price, :weight, :catalog_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/catalogs/_catalog_row.html.erb
<tr id="catalog_<%= catalog.id %>">
	<td><%= catalog.name %></td>
	<td><%= catalog.code %></td>
	<td><%= catalog.quantity %></td>
	<td><% if catalog.products.length > 0 %>
		<% catalog.products.each do |prod| %>
			<ul>
				<li><%= prod.name %></li>
			</ul>
		<% end %>
	<% else %> No product
	<% end %></td>
	<td><%= link_to 'Show catalog', catalog %> | 
	    <%= link_to "Edit catalog", edit_catalog_path(catalog), remote: true %> | 
	    <%= link_to 'Delete catalog', catalog, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
</tr>

app/views/catalogs/_form.html.erb
<div id="catalog-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= params[:action] %>catalog</h4>
      </div>
      <%= form_for @catalog, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div class="form-group">
          <%= f.label :code %>
          <%= f.text_field :code %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/catalogs/create.js.erb
<% if @catalog.errors.blank? %>
  $('#catalog-modal').modal('hide');
  $('table tbody').append('<%= j render "catalog_row", catalog: @catalog %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/catalogs/destroy.js.erb
$("#catalog_<%=@catalog.id%>").remove();

app/views/catalogs/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/catalogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catalogs</h1>

<table class="table" id="catalogs">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Number of products</th>
      <th>Products</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @catalogs.each do |catalog| %>
      <%= render 'catalog_row', catalog: catalog %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Catalog", new_catalog_path, remote: true, class: "btn btn-primary" %>

app/views/catalogs/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/catalogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @catalog.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @catalog.code %>
</p>

<p>
  <strong>Number of products:</strong>
  <%= @catalog.quantity %>
</p>

<% if @catalog.products.length > 0 %>
	<p>
	  <strong>Products:</strong>
	</p>
	<ul id="products">
	  <% @catalog.products.each do |product| %>
		<%= render 'products/product_row', product: product %>
	  <% end %>
	</ul>
<% end %>

<%= link_to "New product", new_catalog_product_path(@catalog), remote: true, class: "btn btn-primary" %>
</p></br></br>

<%= link_to "Edit catalog", edit_catalog_path(@catalog), remote: true %> |
<%= link_to 'Back to catalogs', catalogs_path %>

app/views/catalogs/update.js.erb
<% if @catalog.errors.blank? %>
  $('#catalog-modal').modal('hide');
  $("#catalog_<%=@catalog.id%>").replaceWith('<%= j render "catalog_row", catalog: @catalog %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeleyCatalogue</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= params[:action] %>Product</h4>
      </div>
      <% url = if params[:action] == "edit" %>
        <% {:controller => "products", :action => "update"} %>
      <% elsif params[:action] == "new" %>
        <% catalog_products_path %>
      <% end %>
      <%= form_for @product, url: url, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :code %>
          <%= f.text_field :code, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :price %>
          <%= f.number_field :price, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :weight %>
          <%= f.number_field :weight, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product_row.html.erb
<% object = if params[:action] == "show" %>
  <% product %>
<% elsif params[:action] == "create" || params[:action] == "update" %>
  <% @product %>
<% end %>
<li id="product_<%= product.id %>"><%= link_to product.name, {:controller => "products", :action => "show", :id => product.id, :catalog_id => (params[:catalog_id] || @catalog.id)}%> | <%= link_to "Edit product", {:controller => "products", :action => "edit", :id => product.id, :catalog_id => (params[:catalog_id] || @catalog.id)}, remote: true %> | <%= link_to 'Delete product', {:controller => "products", :action => "destroy", :id => product.id, :catalog_id => (params[:catalog_id] || @catalog.id)}, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
</li>

app/views/products/create.js.erb
<% if @product.errors.blank? %>
  $('#product-modal').modal('hide');
  $("#products").append('<%= j render "product_row", product: @product %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/products/destroy.js.erb
$("#product_<%=@product.id%>").remove();

app/views/products/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Description</th>
      <th>Price</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.code %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.weight %></td>
        <% if product.catalog %>
          <td><%= product.catalog.name %></td>
        <% end %>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @product.weight %>
</p>
</br></br>

<%= link_to "Back to catalog", {:controller => "catalogs", :action => "show", :id => (params[:catalog_id] || @catalog.id)} %>

app/views/products/update.js.erb
<% if @product.errors.blank? %>
  $('#product-modal').modal('hide');
  $("#product_<%=@product.id%>").replaceWith('<%= j render "product_row", product: @product %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>